version: 2
jobs:
  print_hello:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output      
  print_world:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo " World"  
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Something wrong!"; exit 1
          fi
workflows:
  version: 2
  print_hello_world:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
